spring.application.name=liquibase
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Properties
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
logging.level.org.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG